### ISSUE TITLE
Failed to get token from ECS Metadata Service. HttpCode=405

### ISSUE THREAD

**Issue by naico-wang** [aliyun/credentials-nodejs#111]
```
const credConfig = new Credential.Config(config)
try {
    const cred = new Credential.default(credConfig)
    const accessKeyId = await cred.getAccessKeyId()
    const accessKeySecret = await cred.getAccessKeySecret()
    const securityToken = await cred.getSecurityToken()

    console.log('[LOG] - cred:', cred)

    return { accessKeyId, accessKeySecret, securityToken }
  } catch (err) {
    console.log('[Error] - ', err)
  }
```

报错，Failed to get token from ECS Metadata Service. HttpCode=405

**Comment by naico-wang** [comment]
"@alicloud/credentials": "^2.3.0"

**Comment by naico-wang** [comment]
NPM package code: 
![image](https://github.com/user-attachments/assets/78d665db-a903-4ca3-b0ce-9e5fbca60e0b)

**Comment by naico-wang** [comment]
Code inside this repo:
<img width="794" alt="image" src="https://github.com/user-attachments/assets/da139fdb-0dad-49c9-9c63-02c36089b1be">
NPM version missed the method definition.

**Comment by naico-wang** [comment]
@jasonHzq @yndu13 能帮忙看看么？

**Comment by JacksonTian** [comment]
Please use it follow readme:

```
import Credential, { Config } from '@alicloud/credentials';
const config: Config = {
  type:                 'ecs_ram_role',       // credential type
  roleName:             'roleName',           // `roleName` is optional. It will be retrieved automatically if not set. It is highly recommended to set it up to reduce requests.
  disableIMDSv1:         true,                 // `disableIMDSv1` is optional and is recommended to be turned on. It can be replaced by setting environment variable: ALIBABA_CLOUD_IMDSV1_DISABLED
}
const cred = new Credential(config);
const {
  accessKeyId,
  accessKeySecret,
  securityToken,
  type
} = await cred.getCredential();
```

**Comment by naico-wang** [comment]
> Please use it follow readme:
> 
> ```
> import Credential, { Config } from '@alicloud/credentials';
> const config: Config = {
>   type:                 'ecs_ram_role',       // credential type
>   roleName:             'roleName',           // `roleName` is optional. It will be retrieved automatically if not set. It is highly recommended to set it up to reduce requests.
>   disableIMDSv1:         true,                 // `disableIMDSv1` is optional and is recommended to be turned on. It can be replaced by setting environment variable: ALIBABA_CLOUD_IMDSV1_DISABLED
> }
> const cred = new Credential(config);
> const {
>   accessKeyId,
>   accessKeySecret,
>   securityToken,
>   type
> } = await cred.getCredential();
> ```

我就是这么用的，现在的问题是你们github里面的代码，和npmjs上面发布的package里面的代码不一致，npmjs上面的package代码里面少了method：“put”这一行，导致错误了。

**Comment by naico-wang** [comment]
Package updated and issue fixed.
