### ISSUE TITLE
Readme outdated

### ISSUE THREAD

**Issue by dumplinginsoda** [aliyun/credentials-nodejs#28]
https://github.com/aliyun/credentials-nodejs/blob/master/README.md#1-environment-credentials 

the code load `ALIBABA_CLOUD_ACCESS_KEY_ID` and `ALIBABA_CLOUD_ACCESS_KEY_SECRET`

instead of 
`ALICLOUD_ACCESS_KEY` and `ALICLOUD_SECRET_KEY` (which are the keys mentioned in the readme)

**Comment by JacksonTian** [comment]
Thanks for your feedback. We will update it.
