### ISSUE TITLE
const pkg = kitx.loadJSONSync(path.join(__dirname, '../../package.json'));的问题

### ISSUE THREAD

**Issue by cheungchingli** [aliyun/credentials-nodejs#37]
请问为什么不直接引入呢？使用webpack打包的时候，无法定位package.json。

**Comment by yndu13** [comment]
辛苦提供下报错截图

**Comment by cheungchingli** [comment]
![image](https://user-images.githubusercontent.com/25190239/167312911-0ae5344f-49ef-4dd9-ade0-d919787eb1c6.png)
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/25190239/167312981-84210a1a-f6cf-44da-9248-2cf4ffbbe521.png">

就是红框处代码。因为我所有代码都打包成一个test.js文件的。
```
loadJSONSync(p.default.join(__dirname,"../../package.json"))
```
找不到```package.json```

**Comment by cheungchingli** [comment]
如果是```import packageJson from "../../package.json";```，```webpack```会把json内容打包进```test.js```，并不是查找本地某个文件.

**Comment by peze** [comment]
这个可能你前端浏览器里没法用，这个包是只服务nodejs

**Comment by cheungchingli** [comment]
是nodejs的啊，不是说webpack只能打包前端的

**Comment by cheungchingli** [comment]
我是用webpack结合nodejs使用的，这样的好处是打包成一个bundle.js，我就可以随时迁移项目了，不需要再yarn一遍安装依赖

**Comment by cheungchingli** [comment]
理论上来说，如果是```import pkg from "../../package.json";```
那么tsc之后应该类似这个样子：
![image](https://user-images.githubusercontent.com/25190239/167577445-1514d459-ae53-49c7-975c-1d12f9830996.png)
也就不会出错了。

**Comment by cheungchingli** [comment]
理论上来说，如果是import pkg from "../../package.json";
那么tsc之后应该类似这个样子：
![image](https://user-images.githubusercontent.com/25190239/167578580-201c924e-ddea-4680-9e11-9d93889b04b1.png)

引用该包的项目打包之后，会把该包```package.json```的内容打包进去，就不会出错了。
![image](https://user-images.githubusercontent.com/25190239/167578814-5ce06bf3-3c3b-441d-9c19-691812f6180c.png)

**Comment by peze** [comment]
这个在正常的node环境使用的时候用  __dirname 取绝对路径应该是最准确的，你提供的方案应该也没问题，但是这个不该是webpack打包的时候执行路径有问题吗？

**Comment by JacksonTian** [comment]
该库不承诺在浏览器环境下使用。

**Comment by cheungchingli** [comment]
> 这个在正常的node环境使用的时候用 __dirname 取绝对路径应该是最准确的，你提供的方案应该也没问题，但是这个不该是webpack打包的时候执行路径有问题吗？

你没有get到我的意思

**Comment by cheungchingli** [comment]
> 该库不承诺在浏览器环境下使用。

没有说在浏览器下使用。

**Comment by cheungchingli** [comment]
> 该库不承诺在浏览器环境下使用。



> 这个在正常的node环境使用的时候用 __dirname 取绝对路径应该是最准确的，你提供的方案应该也没问题，但是这个不该是webpack打包的时候执行路径有问题吗？

为什么一定要用__dirname？而不选择import文件？
如果在有node_modules的情况下，该库基于路径读取文件完全没问题。
我只是给出一个建议。在讨论更好的兼容性。

**Comment by cheungchingli** [comment]
或许你认真看我说的点，你就会明白了。

**Comment by cheungchingli** [comment]
或许可以加QQ，我语音说一下？哈哈哈
