### ISSUE TITLE
kitx.loadJSONSync(path.join(__dirname, '../../package.json')) 这一行导致的错误

### ISSUE THREAD

**Issue by lxfriday** [aliyun/credentials-nodejs#38]
错误堆栈
```
notificationsAlerts.ts:40 Error: ENOENT: no such file or directory, open 'c:\Users\xxx\yyy\zzzz\package.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at Object.loadJSONSync (c:\Users\xxx\yyy\zzz\cloud-storage-dashboard\dist\webpack:\cloud-storage-dashboard\node_modules\kitx\lib\index.js:15:1)
at Object../node_modules/@alicloud/credentials/dist/util/helper.js (c:\Users\xxx\yyy\zzz\cloud-storage-dashboard\dist\webpack:\cloud-storage-dashboard\node_modules\@alicloud\credentials\dist\util\helper.js:29:1)
```
错误原因，代码被 webpack 编译出来之后由于编译出来的文件目录结构发生了变化，导致下面这一行找不到指定文件
```js
const pkg = kitx.loadJSONSync(path.join(__dirname, '../../package.json'));
```
建议改成直接 `import pkgJSON from '../../package.json'`

**Comment by weirui88888** [comment]
> 
你好，我这边也是报相似的错，请问我应该怎么处理？

**Comment by weirui88888** [comment]
> 错误堆栈
> 
> ```
> notificationsAlerts.ts:40 Error: ENOENT: no such file or directory, open 'c:\Users\xxx\yyy\zzzz\package.json'
>     at Object.openSync (node:fs:585:3)
>     at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
>     at Object.readFileSync (node:fs:453:35)
>     at Object.readFileSync (node:electron/js2c/asar_bundle:5:9160)
>     at Object.loadJSONSync (c:\Users\xxx\yyy\zzz\cloud-storage-dashboard\dist\webpack:\cloud-storage-dashboard\node_modules\kitx\lib\index.js:15:1)
> at Object../node_modules/@alicloud/credentials/dist/util/helper.js (c:\Users\xxx\yyy\zzz\cloud-storage-dashboard\dist\webpack:\cloud-storage-dashboard\node_modules\@alicloud\credentials\dist\util\helper.js:29:1)
> ```
> 
> 错误原因，代码被 webpack 编译出来之后由于编译出来的文件目录结构发生了变化，导致下面这一行找不到指定文件
> 
> ```js
> const pkg = kitx.loadJSONSync(path.join(__dirname, '../../package.json'));
> ```
> 
> 建议改成直接 `import pkgJSON from '../../package.json'`

你好，我这边也是报相似的错，请问我应该怎么处理？

**Comment by lxfriday** [comment]
用这个库 ![patch-package](https://www.npmjs.com/package/patch-package)，我把源代码按照上面的方式修改之后编译出来，然后复制到 node_modules 中，用 patch-package 把 node_modules 的更改记录下来

> > 错误堆栈
> > ```
> > notificationsAlerts.ts:40 Error: ENOENT: no such file or directory, open 'c:\Users\xxx\yyy\zzzz\package.json'
> >     at Object.openSync (node:fs:585:3)
> >     at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
> >     at Object.readFileSync (node:fs:453:35)
> >     at Object.readFileSync (node:electron/js2c/asar_bundle:5:9160)
> >     at Object.loadJSONSync (c:\Users\xxx\yyy\zzz\cloud-storage-dashboard\dist\webpack:\cloud-storage-dashboard\node_modules\kitx\lib\index.js:15:1)
> > at Object../node_modules/@alicloud/credentials/dist/util/helper.js (c:\Users\xxx\yyy\zzz\cloud-storage-dashboard\dist\webpack:\cloud-storage-dashboard\node_modules\@alicloud\credentials\dist\util\helper.js:29:1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 错误原因，代码被 webpack 编译出来之后由于编译出来的文件目录结构发生了变化，导致下面这一行找不到指定文件
> > ```js
> > const pkg = kitx.loadJSONSync(path.join(__dirname, '../../package.json'));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 建议改成直接 `import pkgJSON from '../../package.json'`
> 
> 你好，我这边也是报相似的错，请问我应该怎么处理？

用这个库 ![patch-package](https://www.npmjs.com/package/patch-package)，我把源代码按照上面的方式修改之后编译出来，然后复制到 node_modules 中，用 patch-package 把 node_modules 的更改记录下来

**Comment by lxfriday** [comment]
@weirui88888 我的项目地址 [https://github.com/lxfriday/cloud-storage-dashboard](https://github.com/lxfriday/cloud-storage-dashboard)

**Comment by weirui88888** [comment]
> @weirui88888 我的项目地址 https://github.com/lxfriday/cloud-storage-dashboard

谢了 我直接把你的clone下来，然后把你里面的文件，替换原文件了。

**Comment by weirui88888** [comment]
> > > 错误堆栈
> > > ```
> > > notificationsAlerts.ts:40 Error: ENOENT: no such file or directory, open 'c:\Users\xxx\yyy\zzzz\package.json'
> > >     at Object.openSync (node:fs:585:3)
> > >     at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
> > >     at Object.readFileSync (node:fs:453:35)
> > >     at Object.readFileSync (node:electron/js2c/asar_bundle:5:9160)
> > >     at Object.loadJSONSync (c:\Users\xxx\yyy\zzz\cloud-storage-dashboard\dist\webpack:\cloud-storage-dashboard\node_modules\kitx\lib\index.js:15:1)
> > > at Object../node_modules/@alicloud/credentials/dist/util/helper.js (c:\Users\xxx\yyy\zzz\cloud-storage-dashboard\dist\webpack:\cloud-storage-dashboard\node_modules\@alicloud\credentials\dist\util\helper.js:29:1)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 错误原因，代码被 webpack 编译出来之后由于编译出来的文件目录结构发生了变化，导致下面这一行找不到指定文件
> > > ```js
> > > const pkg = kitx.loadJSONSync(path.join(__dirname, '../../package.json'));
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 建议改成直接 `import pkgJSON from '../../package.json'`
> > 
> > 
> > 你好，我这边也是报相似的错，请问我应该怎么处理？
> 
> 用这个库 [patch-package](https://www.npmjs.com/package/patch-package)，我把源代码按照上面的方式修改之后编译出来，然后复制到 node_modules 中，用 patch-package 把 node_modules 的更改记录下来

按照你的做法，我把源码拉下来之后，改下package.json的引用方式后，发现构建产物多了个src目录。不知道什么情况。看你fork的仓库中，也有dist/src这个目录

**Comment by jeffrey-lunaon** [comment]
碰到了同样的错误，云函数上打包过的文件没有 package.json

**Comment by jeffrey-lunaon** [comment]
我这里选择的解决方案是打包前直接注释掉 dist/ 的引用并填写固定值，希望官方早日出解决方案，比如每次打包自动生成这个 version 而非依赖 package.json 读取。

node_modules/@alicloud/credentials/dist/util/helper.js
```js
// const kitx_1 = __importDefault(require("kitx"));
// const path_1 = __importDefault(require("path"));
// const pkg = kitx_1.default.loadJSONSync(path_1.default.join(__dirname, '../../package.json'));
exports.DEFAULT_UA = `AlibabaCloud (${os.platform()}; ${os.arch()}) ` +
    `Node.js/${process.version} Core/2.2.3`;
exports.DEFAULT_CLIENT = `Node.js(${process.version}), @alicloud/credentials: 2.2.3`;
```
